/**
 * Type definitions for partner lists.
 *
 * A PartnerList is a named, persisted collection of PARTNER_NAME values
 * the user can activate as a cross-app filter. Lists are either
 * attribute-driven (derived from ACCOUNT_TYPE etc. and refreshable),
 * manual/hand-picked snapshots, or auto-maintained `'derived'` lists
 * generated by `computeDerivedLists` (one per distinct ACCOUNT_TYPE
 * value in the dataset).
 *
 * Phase 39 attribute scope: ACCOUNT_TYPE, PRODUCT_TYPE (display alias),
 * SEGMENT (references SegmentRule.name from usePartnerConfig). Phase 44 VOC-05
 * extends with REVENUE_MODEL as the third unit-of-analysis dimension; see
 * docs/adr/0002-revenue-model-scoping.md. New keys land here as `.optional()`
 * fields (additive evolution) so legacy pre-Phase-39/44 lists parse cleanly.
 */

/** Supported attribute keys for attribute-driven partner lists. */
export type AttributeKey =
  | 'ACCOUNT_TYPE'
  | 'PRODUCT_TYPE'
  | 'SEGMENT'
  | 'REVENUE_MODEL';

/**
 * Multi-select filter shape used to derive attribute lists.
 * Within an attribute, values are OR'd. Across attributes, keys are AND'd.
 * An empty / undefined attribute entry means "no constraint on this attribute".
 */
export interface PartnerListFilters {
  /** ACCOUNT_TYPE multi-select; values are OR'd within this attribute. */
  ACCOUNT_TYPE?: string[];
  /**
   * PRODUCT_TYPE — display alias of ACCOUNT_TYPE (same underlying values,
   * different label in UI). Evaluator treats this identically to ACCOUNT_TYPE;
   * if both are set the cross-attribute AND semantics intersect them.
   */
  PRODUCT_TYPE?: string[];
  /**
   * SEGMENT — references SegmentRule.name values from the partner-config
   * (Plan 39-02). Evaluator requires a `segmentResolver` callback to map
   * `(partner, product) → SegmentRule[]` at evaluation time; without one
   * the SEGMENT filter is skipped with a warning.
   */
  SEGMENT?: string[];
  /**
   * Phase 44 VOC-05 — REVENUE_MODEL multi-select against the third dimension
   * of the unit of analysis (CONTINGENCY, DEBT_SALE). Evaluator handles this
   * with the same cross-attribute AND / within-array OR semantics as
   * ACCOUNT_TYPE; rows missing a REVENUE_MODEL field degrade defensively
   * (no match) — same convention as missing PRODUCT_TYPE today.
   *
   * Additive `.optional()` Phase 39 schema-evolution pattern: legacy lists
   * (no REVENUE_MODEL key) parse and evaluate identically to pre-change.
   */
  REVENUE_MODEL?: string[];
  // Future attributes added here as `.optional()` fields (additive evolution).
}

/** A named, persisted partner list. */
export interface PartnerList {
  /** Unique identifier (crypto.randomUUID() for user lists; stable prefix-based for derived). */
  id: string;
  /** User-visible name, required, trimmed before storage. */
  name: string;
  /** Snapshot of matching PARTNER_NAME values at creation/refresh time. */
  partnerIds: string[];
  /** Attribute filter inputs; `{}` when the list was hand-picked only. */
  filters: PartnerListFilters;
  /**
   * Creation mode locked at save time (Pitfall 7):
   * - 'attribute' — derived from filters; gets a Refresh action.
   * - 'manual'    — hand-picked snapshot; no Refresh action.
   * - 'derived'   — auto-maintained by `computeDerivedLists`. Re-derives on
   *                 every hydration; never persisted to localStorage; deletion
   *                 is a no-op (the list re-materializes on next render).
   * Never mutated after creation.
   */
  source: 'attribute' | 'manual' | 'derived';
  /** Creation timestamp (Date.now()). */
  createdAt: number;
  /** Last-updated timestamp (Date.now()). */
  updatedAt: number;
}
